### PR TITLE
fix: load configuration from env_tokens for checkout plugin

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
None (When the checkout plugin was deployed we noticed that the configuration added by the plugin was not getting picked up in the actual edX environment)

#### What's this PR do?
- loads the configuration values from the extended edX settings.

#### How should this be manually tested?
Nothing specific to test but it should load the configuration value in an actual edX instance.

#### Deployemnt:
I've bumped the version for this and we need to update and push a new release for this `ol-openedx-checkout-external` to PyPI followed by a rebuild of our edX MITxOnline-QA instance. @rhysyngsun @blarghmatey

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1:

**Comment by arslanashraf7** [comment]
@blarghmatey Thanks for reviewing the PR.

The post checks would be to update this package on PyPI and a rebuild of the MITXOnline-QA edx-platform to pick up the new version `0.1.1`. Would it be fine to ask you for the plugin update on PyPI since you've been updating the `ol-openedx-` packages on PyPI?

**Comment by blarghmatey** [comment]
I published the updated package to PyPI and rebuilt the image which is now deployed to QA for testing.

**Comment by arslanashraf7** [comment]
@blarghmatey Thanks for publishing the package and the rebuild.

@rhysyngsun, @briangrossman The external checkout redirect itself is now working fine and can be tested in [This Test Course](https://courses-qa.mitxonline.mit.edu/learn/course/course-v1:Arbisoft+ARB_TEST_CKT_001+1/home) where the Course Modes have been configured. But currently upon the redirect, the MITxOnline currently leads to an empty cart or the existing cart without the course through which the redirect happened. Is this the correct behavior or MITxOnline marketing site is not properly handling the link.

**Comment by briangrossman** [comment]
FYI: I created a product (in the admin) for this course (set to $125).

I noticed the same behavior @arslanashraf7 mentioned above where it appears to pick up the existing cart (the course that was added to the cart previously) rather than adding this course to the cart. I have a walkthrough in the video below:

https://user-images.githubusercontent.com/21342568/170093655-512f9caa-97c3-43bc-830f-6f718595122d.mov

Also, where is the price set? We'll ultimately need it to match the price we set in the Product within Ecommerce.
image

**Comment by arslanashraf7** [comment]
FYI @briangrossman.

>Also, where is the price set? We'll ultimately need it to match the price we set in the Product within Ecommerce.

The price should be set in the `Verified` Course mode created for a single course. You can check the price for the test checkout course [here](https://courses-qa.mitxonline.mit.edu/admin/course_modes/coursemode/18/change/).

**Pull request merged**
